// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dimdnnhgzhqmmbskmnts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbWRubmhnemhxbW1ic2ttbnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTQ5MzcsImV4cCI6MjA2NDI5MDkzN30.5YlcB7IPFeSXem_Ne3uJp-XCtNPFmfXZDAyo53NSjhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);